[build-system]
requires = ["setuptools>=61.0", "pybind11>=2.9.0", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "heatmaps_to_keypoints"
version = "0.0.4"
authors = [{ name = "Mwangi Kuya" }]
description = "Fast heatmap-to-keypoints decoder for 2D human pose estimation."
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
dependencies = ["opencv-python >= 4.0"]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.setuptools]

[tool.cibuildwheel.windows]
repair-wheel-command = "delvewheel repair --add-path C:\\tools\\opencv\\build\\x64\\vc15\\bin;C:\\tools\\opencv\\build\\x64\\vc14\\bin;C:\\tools\\opencv\\build\\x64\\vc16\\bin;C:\\opencv\\build\\x64\\vc15\\bin;C:\\opencv\\build\\x64\\vc14\\bin;C:\\opencv\\build\\x64\\vc16\\bin -w {dest_dir} {wheel}"
